export const scholarships = [
	{
		scholarshipsID:"1",
		image : `${process.env.PUBLIC_URL}/images/27f0b6c1-d953-4658-bca8-20cf7eebf69c.jpeg`,
    imageAlt : "scholarship imag",
    title : "Western",
    description : "ប្អូនៗដែលចង់មកសាកសួរព័ត៌មានចុះឈ្មោះចូលរៀននិងទិញពាក្យប្រឡងអាហារូបករណ៍បុគ្គលិកផ្នែកផ្តល់ព័ត៌មានធ្វើការធម្មតាក្នុងឱកាសបុណ្យអុំទូកនេះ។ 1",
    facebookLink : "https://www.facebook.com/pineapplecompany/",
    instagramLink : "https://www.instagram.com/pineapplecompany/",
    websiteLink : "https://pineapplecompany.com/",
    location : "Phnom Penh",
    deadLine : "19/10/2024",
    university:"Western",
    status:'Closed'
	},
	{
		scholarshipsID:"2",
		image : `${process.env.PUBLIC_URL}/images/27f0b6c1-d953-4658-bca8-20cf7eebf69c.jpeg`,
    imageAlt : "scholarship imag",
    title : "TECHNO",
    description : "ប្អូនៗដែលចង់មកសាកសួរព័ត៌មានចុះឈ្មោះចូលរៀននិងទិញពាក្យប្រឡងអាហារូបករណ៍បុគ្គលិកផ្នែកផ្តល់ព័ត៌មានធ្វើការធម្មតាក្នុងឱកាសបុណ្យអុំទូកនេះ។ 2",
    facebookLink : "https://www.facebook.com/pineapplecompany/",
    instagramLink : "https://www.instagram.com/pineapplecompany/",
    websiteLink : "https://pineapplecompany.com/",
    location : "Phnom Penh",
    deadLine : "10/10/2022",
    university:"TECHNO",
    status:'Closed'
	},
	{
		scholarshipsID:"3",
		image : `${process.env.PUBLIC_URL}/images/27f0b6c1-d953-4658-bca8-20cf7eebf69c.jpeg`,
    imageAlt : "scholarship imag",
    title : "RUPP",
    description : "ប្អូនៗដែលចង់មកសាកសួរព័ត៌មានចុះឈ្មោះចូលរៀននិងទិញពាក្យប្រឡងអាហារូបករណ៍បុគ្គលិកផ្នែកផ្តល់ព័ត៌មានធ្វើការធម្មតាក្នុងឱកាសបុណ្យអុំទូកនេះ។ 3 ",
    facebookLink : "https://www.facebook.com/pineapplecompany/",
    instagramLink : "https://www.instagram.com/pineapplecompany/",
    websiteLink : "https://pineapplecompany.com/",
    location : "Siem Reap",
    deadLine : "10/10/2022",
    university:"RUPP",
		status:'Open',
	},
	{
		scholarshipsID:"4",
		image : `${process.env.PUBLIC_URL}/images/27f0b6c1-d953-4658-bca8-20cf7eebf69c.jpeg`,
    imageAlt : "scholarship imag",
    title : "Scholarship",
    description : "ប្អូនៗដែលចង់មកសាកសួរព័ត៌មានចុះឈ្មោះចូលរៀននិងទិញពាក្យប្រឡងអាហារូបករណ៍បុគ្គលិកផ្នែកផ្តល់ព័ត៌មានធ្វើការធម្មតាក្នុងឱកាសបុណ្យអុំទូកនេះ។ 4",
    facebookLink : "https://www.facebook.com/pineapplecompany/",
    instagramLink : "https://www.instagram.com/pineapplecompany/",
    websiteLink : "https://pineapplecompany.com/",
    location : "Siem Reap",
    deadLine : "10/10/2022",
    university:"RUFA",
		status:'Closed'
	},
	{
		scholarshipsID:"1",
		image : `${process.env.PUBLIC_URL}/images/27f0b6c1-d953-4658-bca8-20cf7eebf69c.jpeg`,
    imageAlt : "scholarship imag",
    title : "Western",
    description : "ប្អូនៗដែលចង់មកសាកសួរព័ត៌មានចុះឈ្មោះចូលរៀននិងទិញពាក្យប្រឡងអាហារូបករណ៍បុគ្គលិកផ្នែកផ្តល់ព័ត៌មានធ្វើការធម្មតាក្នុងឱកាសបុណ្យអុំទូកនេះ។ 1",
    facebookLink : "https://www.facebook.com/pineapplecompany/",
    instagramLink : "https://www.instagram.com/pineapplecompany/",
    websiteLink : "https://pineapplecompany.com/",
    location : "Siem Reap",
    deadLine : "19/10/2024",
    university:"Western",
    status:'Closed'
	},
	{
		scholarshipsID:"2",
		image : `${process.env.PUBLIC_URL}/images/27f0b6c1-d953-4658-bca8-20cf7eebf69c.jpeg`,
    imageAlt : "scholarship imag",
    title : "TECHNO",
    description : "ប្អូនៗដែលចង់មកសាកសួរព័ត៌មានចុះឈ្មោះចូលរៀននិងទិញពាក្យប្រឡងអាហារូបករណ៍បុគ្គលិកផ្នែកផ្តល់ព័ត៌មានធ្វើការធម្មតាក្នុងឱកាសបុណ្យអុំទូកនេះ។ 2",
    facebookLink : "https://www.facebook.com/pineapplecompany/",
    instagramLink : "https://www.instagram.com/pineapplecompany/",
    websiteLink : "https://pineapplecompany.com/",
    location : "Phnom Penh",
    deadLine : "10/10/2022",
    university:"TECHNO",
    status:'Closed'
	},
	{
		scholarshipsID:"3",
		image : `${process.env.PUBLIC_URL}/images/27f0b6c1-d953-4658-bca8-20cf7eebf69c.jpeg`,
    imageAlt : "scholarship imag",
    title : "RUPP",
    description : "ប្អូនៗដែលចង់មកសាកសួរព័ត៌មានចុះឈ្មោះចូលរៀននិងទិញពាក្យប្រឡងអាហារូបករណ៍បុគ្គលិកផ្នែកផ្តល់ព័ត៌មានធ្វើការធម្មតាក្នុងឱកាសបុណ្យអុំទូកនេះ។ 3 ",
    facebookLink : "https://www.facebook.com/pineapplecompany/",
    instagramLink : "https://www.instagram.com/pineapplecompany/",
    websiteLink : "https://pineapplecompany.com/",
    location : "Phnom Penh",
    deadLine : "10/10/2022",
    university:"RUPP",
		status:'Open',
	},
	{
		scholarshipsID:"4",
		image : `${process.env.PUBLIC_URL}/images/27f0b6c1-d953-4658-bca8-20cf7eebf69c.jpeg`,
    imageAlt : "scholarship imag",
    title : "Scholarship",
    description : "ប្អូនៗដែលចង់មកសាកសួរព័ត៌មានចុះឈ្មោះចូលរៀននិងទិញពាក្យប្រឡងអាហារូបករណ៍បុគ្គលិកផ្នែកផ្តល់ព័ត៌មានធ្វើការធម្មតាក្នុងឱកាសបុណ្យអុំទូកនេះ។ 4",
    facebookLink : "https://www.facebook.com/pineapplecompany/",
    instagramLink : "https://www.instagram.com/pineapplecompany/",
    websiteLink : "https://pineapplecompany.com/",
    location : "Phnom Penh",
    deadLine : "10/10/2022",
    university:"RUFA",
		status:'Closed'
	},
]